/**
 * @see {@link https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key}
 */
export type KeyboardEvent__modifier_key_T =
	'Alt'
	|'AltGraph'
	|'CapsLock'
	|'Control'
	|'Escape'
	|'Fn'
	|'FnLock'
	|'Hyper'
	|'Meta'
	|'NumLock'
	|'ScrollLock'
	|'Shift'
	|'Super'
	|'Symbol'
	|'SymbolLock'
export type KeyboardEvent__whitespace_key_T = 'Enter'|'Tab'|' '
export type KeyboardEvent__navigation_key_T = 'ArrowDown'|'ArrowLeft'|'ArrowRight'|'ArrowUp'|'End'|'Home'|'PageDown'|'PageUp'
export type KeyboardEvent__function_key_T =
	'F1'
	|'F2'
	|'F3'
	|'F4'
	|'F5'
	|'F6'
	|'F7'
	|'F8'
	|'F9'
	|'F10'
	|'F11'
	|'F12'
	|'F13'
	|'F14'
	|'F15'
	|'F16'
	|'F17'
	|'F18'
	|'F19'
	|'F20'
	|'Soft1'
	|'Soft2'
	|'Soft3'
	|'Soft4'
export type KeyboardEvent__numeric_keypad_key_T =
	'Decimal'
	|'Key11'
	|'Key12'
	|'Multiply'
	|'Add'
	|'Clear'
	|'Divide'
	|'Subtract'
	|'Separator'
	|'0'
	|'1'
	|'2'
	|'3'
	|'4'
	|'5'
	|'6'
	|'7'
	|'8'
	|'9'
export type KeyboardEvent__key_T =
	KeyboardEvent__modifier_key_T
	|KeyboardEvent__whitespace_key_T
	|KeyboardEvent__navigation_key_T
	|KeyboardEvent__function_key_T
	|KeyboardEvent__numeric_keypad_key_T
